
blacklist = ['123456', 'porsche', 'firebird', 'prince', 'rosebud',
 'password', 'guitar', 'butter', 'beach', 'jaguar', '12345678', 'chelsea',
 'united', 'amateur', 'great', '1234', 'black', 'turtle', '7777777', 
 'cool', 'pussy', 'diamond', 'steelers', 'muffin', 'cooper', '12345', 
 'nascar', 'tiffany', 'redsox', '1313', 'dragon', 'jackson', 'zxcvbn', 'star',
 'scorpio', 'qwerty', 'cameron', 'tomcat', 'testing', 'mountain', '696969', 
 '654321', 'golf', 'shannon', 'madison', 'mustang', 'computer', 'bond007', 
 'murphy', '987654', '11', 'letmein', 'amanda', 'bear', 'frank', 'brazil', 
 '12', 'baseball', 'wizard', 'tiger', 'hannah', 'lauren', '13', 'master', 
 'xxxxxxxx', 'doctor', 'dave', 'japan', '14', 'michael', 'money', 'gateway',
 'eagle1', 'naked', '15', 'football', 'phoenix', 'gators', '11111', 'squirt',
 '16', 'shadow', 'mickey', 'angel', 'mother', 'stars', '17', 'monkey', 
 'bailey', 'junior', 'nathan', 'apple', '18', 'abc123', 'knight', 'thx1138',
 'raiders', 'alexis', '19', 'pass', 'iceman', 'porno', 'steve', 'aaaa', '20', 
 'fuckme', 'tigers', 'badboy', 'forever', 'bonnie', '21', '6969', 'purple', 
 'debbie', 'angela', 'peaches', '22', 'jordan', 'andrea', 'spider', 'viper',
 'jasmine', '23', 'harley', 'horny', 'melissa', 'ou812', 'kevin', '24', 
 'ranger', 'dakota', 'booger', 'jake', 'matt', '25', 'iwantu', 'aaaaaa',
 '1212', 'lovers', 'qwertyui', '26', 'jennifer', 'player', 'flyers', 
 'suckit', 'danielle', '27', 'hunter', 'sunshine', 'fish', 'gregory',
 'beaver', '28', 'fuck', 'morgan', 'porn', 'buddy', '4321', '29', '2000',
 'starwars', 'matrix', 'whatever', '4128', '30', 'test', 'boomer', 'teens',
 'young', 'runner', '31', 'batman', 'cowboys', 'scooby', 'nicholas',
 'swimming', '32', 'trustno1', 'edward', 'jason', 'lucky', 'dolphin', '33',
 'thomas', 'charles', 'walter', 'helpme', 'gordon', '34', 'tigger', 'girls',
 'cumshot', 'jackie', 'casper', '35', 'robert', 'booboo', 'boston', 'monica',
 'stupid', '36', 'access', 'coffee', 'braves', 'midnight', 'shit', '37',
 'love', 'xxxxxx', 'yankee', 'college', 'saturn', '38', 'buster', 
 'bulldog', 'lover', 'baby', 'gemini', '39', '1234567', 'ncc1701', 
 'barney', 'cunt', 'apples', '40', 'soccer', 'rabbit', 'victor', 'brian',
 'august', '41', 'hockey', 'peanut', 'tucker', 'mark', '3333', '42', 
 'killer', 'john', 'princess', 'startrek', 'canada', '43', 'george', 
 'johnny', 'mercedes', 'sierra', 'blazer', '44', 'sexy', 'gandalf', 
 '5150', 'leather', 'cumming', '45', 'andrew', 'spanky', 'doggie', 
 '232323', 'hunting', '46', 'charlie', 'winter', 'zzzzzz', '4444', 
 'kitty', '47', 'superman', 'brandy', 'gunner', 'beavis', 'rainbow',
 '48', 'asshole', 'compaq', 'horney', 'bigcock', '112233', '49', 'fuckyou',
 'carlos', 'bubba', 'happy', 'arthur', '50', 'dallas', 'tennis', '2112', 
 'sophie', 'cream', '51', 'jessica', 'james', 'fred', 'ladies', 'calvin', 
 '52', 'panties', 'mike', 'johnson', 'naughty', 'shaved', '53', 'pepper', 
 'brandon', 'xxxxx', 'giants', 'surfer', '54', '1111', 'fender', 'tits', 
 'booty', 'samson', '55', 'austin', 'anthony', 'member', 'blonde', 'kelly', 
 '56', 'william', 'blowme', 'boobs', 'fucked', 'paul', '57', 'daniel', 
 'ferrari', 'donald', 'golden', 'mine', '58', 'golfer', 'cookie', 
 'bigdaddy', '0', 'king', '59', 'summer', 'chicken', 'bronco', 'fire', 
 'racing', '60', 'heather', 'maverick', 'penis', 'sandra', '5555', '61',
 'hammer', 'chicago', 'voyager', 'pookie', 'eagle', '62', 'yankees', 'joseph',
 'rangers', 'packers', 'hentai', '63', 'joshua', 'diablo', 'birdie', 
 'einstein', 'newyork']